# Routes Generales
gmao_moulage_homepage:
    path:     /
    defaults: { _controller: GmaoMoulageBundle:Default:index }

# Routes Presse
gmao_moulage_ajouter_presse:
    path:     /presse/ajouter
    defaults: { _controller: GmaoMoulageBundle:Presse:ajouterPresse }

gmao_moulage_liste_presse:
    path:     /presse/liste/{page}
    defaults: { _controller: GmaoMoulageBundle:Presse:allPresse, page: 1 }
    requirements:
      page: \d*

gmao_moulage_liste_all_presse:
    path:     /presse/liste/all
    defaults: { _controller: GmaoMoulageBundle:Presse:lsAllPresse }

gmao_moulage_modifier_presse:
    path: /presse/modifier/{id}
    defaults: { _controller: GmaoMoulageBundle:Presse:modifierPresse }
    requirements:
      id: \d+

gmao_moulage_supprimer_presse:
    path: /presse/supprimer/{id}
    defaults: { _controller: GmaoMoulageBundle:Presse:supprimerPresse }
    requirements:
      id: \d+

# Routes References
gmao_moulage_ajouter_reference:
    path:     /reference/ajouter
    defaults: { _controller: GmaoMoulageBundle:Reference:ajouterReference }

gmao_moulage_liste_reference:
    path:     /reference/liste/{page}
    defaults: { _controller: GmaoMoulageBundle:Reference:allReference, page: 1 }
    requirements:
      page: \d*

gmao_moulage_modifier_reference:
    path: /reference/modifier/{id}
    defaults: { _controller: GmaoMoulageBundle:Reference:modifierReference }
    requirements:
      id: \d+

gmao_moulage_supprimer_reference:
    path: /reference/supprimer/{id}
    defaults: { _controller: GmaoMoulageBundle:Reference:supprimerReference }
    requirements:
      id: \d+

# Routes Moule
gmao_moulage_ajouter_moule:
    path:     /moule/ajouter
    defaults: { _controller: GmaoMoulageBundle:Moule:ajouterMoule }

gmao_moulage_liste_moule:
    path:     /moule/liste/{page}
    defaults: { _controller: GmaoMoulageBundle:Moule:allMoule, page: 1 }
    requirements:
      page: \d*

gmao_moulage_modifier_moule:
    path: /moule/modifier/{id}
    defaults: { _controller: GmaoMoulageBundle:Moule:modifierMoule }
    requirements:
      id: \d+

gmao_moulage_supprimer_moule:
    path: /moule/supprimer/{id}
    defaults: { _controller: GmaoMoulageBundle:Moule:supprimerMoule }
    requirements:
      id: \d+
      
# Routes LocalisationDefaut
gmao_moulage_ajouter_loc_defaut:
    path:     /loc_defaut/ajouter
    defaults: { _controller: GmaoMoulageBundle:LocalisationDefaut:ajouterLocalisationDefaut }

gmao_moulage_liste_loc_defaut:
    path:     /loc_defaut/liste/{page}
    defaults: { _controller: GmaoMoulageBundle:LocalisationDefaut:allLocalisationDefaut, page: 1 }
    requirements:
      page: \d*

gmao_moulage_modifier_loc_defaut:
    path: /loc_defaut/modifier/{id}
    defaults: { _controller: GmaoMoulageBundle:LocalisationDefaut:modifierLocalisationDefaut }
    requirements:
      id: \d+

gmao_moulage_supprimer_loc_defaut:
    path: /loc_defaut/supprimer/{id}
    defaults: { _controller: GmaoMoulageBundle:LocalisationDefaut:supprimerLocalisationDefaut }
    requirements:
      id: \d+
      
# Routes Equipes
gmao_moulage_ajouter_equipe:
    path:     /equipe/ajouter
    defaults: { _controller: GmaoMoulageBundle:Equipe:ajouterEquipe }

gmao_moulage_liste_equipe:
    path:     /equipe/liste/{page}
    defaults: { _controller: GmaoMoulageBundle:Equipe:allEquipe, page: 1 }
    requirements:
      page: \d*

gmao_moulage_modifier_equipe:
    path: /equipe/modifier/{id}
    defaults: { _controller: GmaoMoulageBundle:Equipe:modifierEquipe }
    requirements:
      id: \d+

gmao_moulage_supprimer_equipe:
    path: /equipe/supprimer/{id}
    defaults: { _controller: GmaoMoulageBundle:Equipe:supprimerEquipe }
    requirements:
      id: \d+

# Routes defaut Niveau1
gmao_moulage_ajouter_defaut_niveau1:
    path:     /defaut_niveau1/ajouter
    defaults: { _controller: GmaoMoulageBundle:DefautNiveau1:ajouterDefautNiveau1 }

gmao_moulage_liste_defaut_niveau1:
    path:     /defaut_niveau1/liste/{page}
    defaults: { _controller: GmaoMoulageBundle:DefautNiveau1:allDefautNiveau1, page: 1 }
    requirements:
      page: \d*

gmao_moulage_modifier_defaut_niveau1:
    path: /defaut_niveau1/modifier/{id}
    defaults: { _controller: GmaoMoulageBundle:DefautNiveau1:modifierDefautNiveau1 }
    requirements:
      id: \d+

gmao_moulage_supprimer_defaut_niveau1:
    path: /defaut_niveau1/supprimer/{id}
    defaults: { _controller: GmaoMoulageBundle:DefautNiveau1:supprimerDefautNiveau1 }
    requirements:
      id: \d+
