<?php

namespace Gmao\MoulageBundle\Entity;

/**
 * PresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresseRepository extends \Doctrine\ORM\EntityRepository
{
}
