Gmao\MoulageBundle\Entity\Presse:
    type: entity
    table: null
    repositoryClass: Gmao\MoulageBundle\Repository\PresseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomPresse:
            type: string
            length: 255
        etatPresse:
            type: boolean
    lifecycleCallbacks: {  }
