<?php

namespace Gmao\MoulageBundle\Repository;

/**
 * AlveoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlveoleRepository extends \Doctrine\ORM\EntityRepository
{
}
