<?php

namespace Gmao\MoulageBundle\Repository;

/**
 * EmpreinteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpreinteRepository extends \Doctrine\ORM\EntityRepository
{
}
