<?php

namespace Gmao\MoulageBundle\Repository;

/**
 * EmpreinteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpreinteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLsEmpreinteTrueParMoule($idMoule) {
		$qb = $this->createQueryBuilder ( 'emp' )
		->join('emp.moule_empreinte', 'moule_emp')
		->where ( 'emp.etatEmpreinte = 1' )
		->andWhere('moule_emp.id = :idMoule')
		->setParameter('idMoule', $idMoule);
		return $qb;
	}
}
