<?php

namespace Gmao\MoulageBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FncRepository extends \Doctrine\ORM\EntityRepository
{
	public function getFncs($nombreParPage, $page) {
		if ($page < 1) {
			throw new \InvalidArgumentException ( 'L\'argument $page ne peut être inférieur à 1 (valeur : "' . $page . '").' );
		}
	
		$query = $this->createQueryBuilder ( 'f' )->getQuery ();
	
		$query->setFirstResult ( ($page - 1) * $nombreParPage )->setMaxResults ( $nombreParPage );
	
		return new Paginator ( $query );
	}
}
