<?php

namespace Gmao\MoulageBundle\Repository;

/**
 * ImageDefautRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageDefautRepository extends \Doctrine\ORM\EntityRepository
{
}
