<?php

namespace Gmao\MoulageBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LocalisationDefautRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalisationDefautRepository extends \Doctrine\ORM\EntityRepository {
	
	public function getLocalisationDefauts($nombreParPage, $page) {
		if ($page < 1) {
			throw new \InvalidArgumentException ( 'L\'argument $page ne peut être inférieur à 1 (valeur : "' . $page . '").' );
		}
		
		$query = $this->createQueryBuilder ( 'l' )->getQuery ();
		
		$query->setFirstResult ( ($page - 1) * $nombreParPage )->setMaxResults ( $nombreParPage );
		
		return new Paginator ( $query );
	}
}
