<?php

namespace Gmao\MoulageBundle\Repository;

/**
 * MouleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouleRepository extends \Doctrine\ORM\EntityRepository
{
}
